'use strict';

/* ═══════════════════════════════════════════════════════════════
   trial-report.js — Trial Evaluation Report: builder, preview, PDF
   - Strengths & Areas of Opportunity via trait chip selection
   - Development Plan auto-generated by Claude API from traits
═══════════════════════════════════════════════════════════════ */

const TrialReport = {

  _player: null,
  _evaluation: null,

  init() {},

  // ── Entry Point ─────────────────────────────────────────────

  async show(playerId) {
    const player = await DB.get(playerId);
    if (!player) { location.hash = '#roster'; return; }

    TrialReport._player = player;
    TrialReport._evaluation = player.trialEvaluation
      ? JSON.parse(JSON.stringify(player.trialEvaluation))
      : TrialReport._emptyEvaluation();

    // Migrate old format
    if (TrialReport._evaluation.traits && !TrialReport._evaluation.strengths) {
      const old = TrialReport._evaluation;
      const ev = TrialReport._emptyEvaluation();
      // Pull strengths/weaknesses from old traits format
      if (old.traits) {
        for (const pillar of Object.values(old.traits)) {
          if (pillar.strengths) ev.strengths.push(...pillar.strengths);
          if (pillar.weaknesses) ev.areasOfOpportunity.push(...pillar.weaknesses);
        }
      }
      ev.generalNotes = old.generalNotes || '';
      ev.recommendation = old.recommendation || '';
      ev.recommendationSummary = old.recommendationSummary || '';
      TrialReport._evaluation = ev;
    }

    const container = document.getElementById('trial-report-content');
    container.innerHTML = TrialReport._renderBuilder(player);
    TrialReport._bindEvents(container);
  },

  _emptyEvaluation() {
    return {
      strengths: [],
      strengthsSentences: [],
      areasOfOpportunity: [],
      areasSentences: [],
      coachNotesRaw: '',
      coachAssessment: '',
      recommendation: '',
      decisionSummary: ''
    };
  },

  // ══════════════════════════════════════════════════════════════
  //  BUILDER FORM
  // ══════════════════════════════════════════════════════════════

  _renderBuilder(player) {
    const name = `${player.firstName} ${player.lastName}`;
    const ev = TrialReport._evaluation;

    return `
      <div class="report-builder">
        <div class="back-row">
          <button class="btn-back" onclick="location.hash='#profile/${player.id}'">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"><polyline points="15 18 9 12 15 6"/></svg>
            Back to Profile
          </button>
        </div>

        <div class="report-builder-header">
          <h2>Trial Evaluation Report</h2>
          <p class="report-builder-sub">${name} &middot; ${player.ageGroup || '—'}</p>
        </div>

        <!-- ── Trait Selection ──────────────────────────────── -->
        <div class="report-section">
          <div class="report-section-title">Player Evaluation</div>
          <p class="report-section-desc">Click to cycle: <span class="trl-legend-s">Strength</span> <span class="trl-legend-a">Area of Opportunity</span></p>
          ${TrialReport._renderTraitSelectors()}
        </div>

        <!-- ── Coaching Staff Assessment ──────────────────────────── -->
        <div class="report-section">
          <div class="report-section-title">Coaching Staff Assessment</div>
          <p class="report-section-desc">Write your impressions of the player, then polish with AI</p>
          <textarea class="report-textarea" id="trl-coach-notes" rows="4" placeholder="Type your rough impressions of the player...">${TrialReport._esc(ev.coachNotesRaw)}</textarea>
          <div class="trl-ai-row">
            <button class="btn btn-ai-generate" id="trl-btn-polish">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/></svg>
              Polish with AI
            </button>
            <button class="btn-reset-key" id="trl-btn-reset-key">Reset API Key</button>
          </div>
          <textarea class="report-textarea trl-assessment-result" id="trl-coach-assessment" rows="6" placeholder="Polished assessment will appear here. You can edit it before exporting." ${ev.coachAssessment ? '' : 'style="display:none"'}>${TrialReport._esc(ev.coachAssessment)}</textarea>
        </div>

        <!-- ── Recommendation ─────────────────────────────── -->
        <div class="report-section">
          <div class="report-section-title">Decision</div>
          <div class="trl-rec-toggle" id="trl-rec-toggle">
            <button type="button" class="trl-rec-btn trl-rec-offer ${ev.recommendation === 'accepted' ? 'active' : ''}" data-rec="accepted">Accepted</button>
            <button type="button" class="trl-rec-btn trl-rec-pass ${ev.recommendation === 'not-accepted' ? 'active' : ''}" data-rec="not-accepted">Not Accepted</button>
          </div>
        </div>

        <!-- ── Actions ────────────────────────────────────── -->
        <div class="report-actions">
          <button class="btn btn-outline" id="trl-btn-save">Save Draft</button>
          <button class="btn btn-primary" id="trl-btn-preview">Preview Report</button>
        </div>

      </div>`;
  },

  _renderTraitSelectors() {
    const ev = TrialReport._evaluation;
    let html = '';

    for (const [pillarKey, pillar] of Object.entries(REPORT_TRAITS)) {
      html += `<div class="trait-pillar">
        <div class="trait-pillar-label">${pillar.label}</div>
        <div class="trait-grid">`;

      for (const [traitKey, traitLabel] of Object.entries(pillar.traits)) {
        let mode = '';
        if (ev.strengths.includes(traitKey)) mode = 'strength';
        else if (ev.areasOfOpportunity.includes(traitKey)) mode = 'area';

        html += `<span class="trait-chip" data-pillar="${pillarKey}" data-trait="${traitKey}" ${mode ? `data-mode="${mode}"` : ''}>${traitLabel}</span>`;
      }

      html += '</div></div>';
    }

    return html;
  },

  // ── Events ──────────────────────────────────────────────────

  _bindEvents(container) {
    // Trait chip click — cycle: none → strength → area → none
    container.querySelectorAll('.trait-chip').forEach(chip => {
      chip.addEventListener('click', () => {
        const trait = chip.dataset.trait;
        const current = chip.dataset.mode || '';
        const ev = TrialReport._evaluation;

        // Remove from both arrays
        ev.strengths = ev.strengths.filter(t => t !== trait);
        ev.areasOfOpportunity = ev.areasOfOpportunity.filter(t => t !== trait);

        if (current === '') {
          ev.strengths.push(trait);
          chip.dataset.mode = 'strength';
        } else if (current === 'strength') {
          ev.areasOfOpportunity.push(trait);
          chip.dataset.mode = 'area';
        } else {
          delete chip.dataset.mode;
        }
      });
    });

    // Polish with AI
    container.querySelector('#trl-btn-polish').addEventListener('click', () => {
      TrialReport._polishAssessment(container);
    });

    // Reset API key
    container.querySelector('#trl-btn-reset-key').addEventListener('click', () => {
      localStorage.removeItem('itp_claude_api_key');
      App.toast('API key cleared');
    });

    // Recommendation toggle
    container.querySelector('#trl-rec-toggle').addEventListener('click', e => {
      const btn = e.target.closest('.trl-rec-btn');
      if (!btn) return;
      const isActive = btn.classList.contains('active');
      container.querySelectorAll('.trl-rec-btn').forEach(b => b.classList.remove('active'));
      if (!isActive) {
        btn.classList.add('active');
        TrialReport._evaluation.recommendation = btn.dataset.rec;
      } else {
        TrialReport._evaluation.recommendation = '';
      }
    });

    // Save draft
    container.querySelector('#trl-btn-save').addEventListener('click', async () => {
      TrialReport._syncFormData(container);
      await TrialReport._saveDraft();
      App.toast('Draft saved');
    });

    // Preview
    container.querySelector('#trl-btn-preview').addEventListener('click', async () => {
      TrialReport._syncFormData(container);
      await TrialReport._saveDraft();
      const btn = container.querySelector('#trl-btn-preview');
      btn.textContent = 'Generating...';
      btn.disabled = true;
      await TrialReport._generateTraitSentences();
      await TrialReport._saveDraft();
      btn.textContent = 'Preview Report';
      btn.disabled = false;
      TrialReport._showPreview(container);
    });
  },

  _syncFormData(container) {
    const ev = TrialReport._evaluation;
    ev.coachNotesRaw = container.querySelector('#trl-coach-notes')?.value || '';
    ev.coachAssessment = container.querySelector('#trl-coach-assessment')?.value || '';
    ev.decisionSummary = container.querySelector('#trl-rec-summary')?.value || '';
  },

  async _saveDraft() {
    const player = TrialReport._player;
    player.trialEvaluation = TrialReport._evaluation;
    await DB.save(player);
  },

  // ══════════════════════════════════════════════════════════════
  //  TRAIT → BULLET POINT FORMATTING
  // ══════════════════════════════════════════════════════════════

  _traitLabel(traitKey) {
    for (const pillar of Object.values(REPORT_TRAITS)) {
      if (pillar.traits[traitKey]) return pillar.traits[traitKey];
    }
    return traitKey;
  },

  _traitPillar(traitKey) {
    for (const [pk, pillar] of Object.entries(REPORT_TRAITS)) {
      if (pillar.traits[traitKey]) return pillar.label;
    }
    return '';
  },

  _groupTraitsByPillar(traitKeys) {
    const groups = {};
    for (const key of traitKeys) {
      const pillar = TrialReport._traitPillar(key);
      if (!groups[pillar]) groups[pillar] = [];
      groups[pillar].push(TrialReport._traitLabel(key));
    }
    return groups;
  },

  // ══════════════════════════════════════════════════════════════
  //  A4 PREVIEW
  // ══════════════════════════════════════════════════════════════

  _showPreview(container) {
    const player = TrialReport._player;
    const ev = TrialReport._evaluation;
    const meta = DB.getMeta();
    const seasonLabel = `20${meta.activeSeason}`;

    const previewArea = document.getElementById('trial-report-preview-standalone');

    const strengthsHtml = TrialReport._renderEvalCard(ev, 'strengths');
    const areasHtml = TrialReport._renderEvalCard(ev, 'areas');

    previewArea.innerHTML = `
      <div class="report-preview-toolbar">
        <button class="btn btn-primary" id="trl-btn-export-pdf">Export PDF</button>
        <button class="btn btn-outline" id="trl-btn-close-preview">Close Preview</button>
      </div>
      <div id="trl-report-pages">
        <div class="rpt-page rpt-page-watermark">
          ${TrialReport._renderHeader(seasonLabel)}
          ${TrialReport._renderPlayerHero(player)}
          ${TrialReport._renderPhysicalPerformance(player)}
          ${strengthsHtml ? '<hr class="rpt-divider">' + strengthsHtml : ''}
        </div>
        <div class="rpt-page rpt-page-watermark rpt-page-continuation">
          ${areasHtml}
          ${areasHtml ? '<hr class="rpt-divider">' : ''}
          ${TrialReport._renderCoachAssessment(ev)}
          <hr class="rpt-divider">
          ${TrialReport._renderRecommendation(ev)}
          ${TrialReport._renderFooter(player)}
        </div>
      </div>`;

    previewArea.scrollIntoView({ behavior: 'smooth' });

    previewArea.querySelector('#trl-btn-export-pdf').addEventListener('click', () => {
      TrialReport._exportPDF();
    });

    previewArea.querySelector('#trl-btn-close-preview').addEventListener('click', () => {
      previewArea.innerHTML = '';
    });
  },

  // ── Header Banner ───────────────────────────────────────────

  _renderHeader(seasonLabel) {
    // Calculate prospect season (next season from active)
    const meta = DB.getMeta();
    const parts = (meta.activeSeason || '25-26').split('-');
    const nextStart = parseInt(parts[1], 10);
    const nextEnd = nextStart + 1;
    const prospectLabel = `Prospect 20${nextStart}-${nextEnd}`;

    return `
      <div class="rpt-header-banner">
        <img src="assets/logos/fc-fs-white.png" alt="" class="rpt-logo">
        <div class="rpt-header-banner-text">
          <div class="rpt-title">Trial Evaluation</div>
          <div class="rpt-subtitle">International Talent Pathway</div>
        </div>
        <div class="rpt-header-right">
          <div class="rpt-season">${prospectLabel}</div>
        </div>
      </div>`;
  },

  // ── Player Hero ─────────────────────────────────────────────

  _renderPlayerHero(player) {
    const age = App.computeAge(player.dateOfBirth);
    const dob = player.dateOfBirth ? new Date(player.dateOfBirth + 'T12:00:00').toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }) : '—';
    const positions = (player.positions || []).map(p => typeof p === 'string' ? p : p.code).join(' / ') || '—';

    let trialPeriod = '—';
    if (player.trialDates?.start && player.trialDates?.end) {
      const fmtDate = (iso) => new Date(iso + 'T12:00:00').toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
      trialPeriod = `${fmtDate(player.trialDates.start)} – ${fmtDate(player.trialDates.end)}, ${new Date(player.trialDates.end + 'T12:00:00').getFullYear()}`;
    } else if (player.trialDates?.start) {
      trialPeriod = new Date(player.trialDates.start + 'T12:00:00').toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
    }

    return `
      <div class="rpt-player-hero">
        <div class="rpt-player-name">${player.firstName} <span class="rpt-player-surname">${player.lastName}</span></div>
        <div class="rpt-player-meta">${player.ageGroup || '—'} &middot; ${positions} &middot; ${player.nationality || '—'}</div>
        <div class="rpt-info-grid">
          <div class="rpt-info-row"><span class="rpt-info-label">Date of Birth</span><span class="rpt-info-value">${dob}</span></div>
          <div class="rpt-info-row"><span class="rpt-info-label">Age</span><span class="rpt-info-value">${age || '—'}</span></div>
          <div class="rpt-info-row"><span class="rpt-info-label">Foot</span><span class="rpt-info-value">${player.foot || '—'}</span></div>
          <div class="rpt-info-row"><span class="rpt-info-label">Trial Period</span><span class="rpt-info-value">${trialPeriod}</span></div>
        </div>
      </div>`;
  },

  // ── Physical Performance ────────────────────────────────────

  _renderPhysicalPerformance(player) {
    const ageGroup = player.ageGroup;
    const tests = player.tests || {};
    const order = ['sprint5m', 'sprint10m', 'sprint20m', 'sprint30m', 'broadJump'];

    const rows = [];
    for (const key of order) {
      const session = DB.getLatestSession(player, key);
      let value = session && session.best != null ? session.best : null;
      if (value == null) continue;
      // Guard: broad jump entered in meters → convert to cm (benchmarks expect cm)
      if (key === 'broadJump' && value > 0 && value < 10) value = Math.round(value * 100);
      rows.push(TrialReport._renderTestRow(ageGroup, key, value));
    }

    const topSpeed = TrialReport._calcMaxSpeed(tests);
    const callout = topSpeed
      ? `<div class="rpt-top-speed-callout">Estimated top speed <strong>${topSpeed} km/h</strong> <span class="rpt-top-speed-note">derived from sprint splits</span></div>`
      : '';

    if (rows.length === 0 && !callout) return '';

    return `
      <div class="rpt-physical-section">
        <div class="rpt-heading">Physical Performance</div>
        <div class="rpt-physical-sub">Latest results vs. German ${ageGroup || ''} academy benchmarks</div>
        <div class="rpt-test-rows">${rows.join('')}</div>
        ${callout}
      </div>`;
  },

  _renderTestRow(ageGroup, testKey, value) {
    const def = TEST_DEFS[testKey];
    if (!def) return '';
    const { level } = Benchmarks.evaluate(ageGroup, testKey, value);
    const thresh = Benchmarks.getThresholds(ageGroup, testKey);
    const lowerIsBetter = !!def.lowerIsBetter;
    const group = def.category === 'Speed' ? 'speed' : 'explosive';

    // Format value: sprints/dribbling 2 decimals, otherwise integer
    const fmt = (v) => def.unit === 's' ? Number(v).toFixed(2) : (Number.isInteger(v) ? v : Number(v).toFixed(1));
    const valueStr = fmt(value);

    let scaleHtml = '';
    if (thresh) {
      const order = [['poor', thresh.poor], ['average', thresh.average], ['good', thresh.good], ['elite', thresh.elite]];
      const marks = order.map(([lvl, val]) => `<div class="rpt-thresh-mark" data-level="${lvl}">${fmt(val)}</div>`).join('');
      const visualPct = TrialReport._computeVisualPct(value, thresh, lowerIsBetter);
      scaleHtml = `
        <div class="rpt-thresh-scale">${marks}</div>
        <div class="rpt-thresh-bar">
          <div class="rpt-thresh-fill" data-level="${level}" style="width:${visualPct}%"></div>
        </div>`;
    }

    return `
      <div class="rpt-test-row" data-level="${level}" data-group="${group}">
        <div class="rpt-test-row-name">${def.name}</div>
        <div class="rpt-test-row-value" data-level="${level}">${valueStr}<span class="rpt-test-row-unit">${def.unit}</span></div>
        <div class="rpt-test-row-bar">${scaleHtml}</div>
      </div>`;
  },

  // Compute fill width that visually aligns with the four threshold mark centers
  // (12.5%, 37.5%, 62.5%, 87.5%) — each mark spans 25% of the bar.
  _computeVisualPct(value, thresh, lowerIsBetter) {
    const { poor, average, good, elite } = thresh;
    const interp = (a, b, base) => {
      const span = a - b;
      if (span === 0) return base + 12.5;
      const ratio = (a - value) / span;
      return base + Math.max(0, Math.min(1, ratio)) * 25;
    };

    if (lowerIsBetter) {
      if (value >= poor)    return Math.max(2, (poor / value) * 12.5);
      if (value >= average) return interp(poor, average, 12.5);
      if (value >= good)    return interp(average, good, 37.5);
      if (value >= elite)   return interp(good, elite, 62.5);
      return Math.min(100, 87.5 + ((elite - value) / elite) * 12.5);
    }
    // higher is better — invert
    if (value <= poor)    return Math.max(2, (value / poor) * 12.5);
    if (value <= average) return 12.5 + ((value - poor) / (average - poor)) * 25;
    if (value <= good)    return 37.5 + ((value - average) / (good - average)) * 25;
    if (value <= elite)   return 62.5 + ((value - good) / (elite - good)) * 25;
    return Math.min(100, 87.5 + ((value - elite) / elite) * 12.5);
  },

  // Derive top speed (km/h) from best sprint splits (mirrors profile.js)
  _calcMaxSpeed(tests) {
    if (!tests) return null;
    const t5  = tests.sprint5m?.best;
    const t10 = tests.sprint10m?.best;
    const t20 = tests.sprint20m?.best;
    const t30 = tests.sprint30m?.best;
    const t40 = tests.sprint40yd?.best;

    const segments = [];
    if (t20 && t30)  segments.push(10   / (t30 - t20));
    if (t30 && t40)  segments.push(6.58 / (t40 - t30));
    if (t10 && t30)  segments.push(20   / (t30 - t10));
    if (t5  && t20)  segments.push(15   / (t20 - t5));
    if (t5  && t10)  segments.push(5    / (t10 - t5));

    if (segments.length === 0) return null;
    const maxMs = Math.max(...segments);
    if (!isFinite(maxMs) || maxMs <= 0) return null;
    return Math.round(maxMs * 3.6 * 10) / 10;
  },

  // ── Two-Column Strengths & Areas ────────────────────────────

  _renderEvalCard(ev, side) {
    const isStrengths = side === 'strengths';
    const items = isStrengths ? ev.strengths : ev.areasOfOpportunity;
    if (!items || items.length === 0) return '';

    const sentences = (isStrengths ? ev.strengthsSentences : ev.areasSentences) || [];
    const cardClass = isStrengths ? 'strengths-card' : 'areas-card';
    const heading = isStrengths ? 'Strengths' : 'Areas of Opportunity';

    let html = `<div class="rpt-eval-section"><div class="rpt-eval-card ${cardClass}">`;
    html += `<div class="rpt-heading">${heading}</div>`;
    html += '<ul class="rpt-bullet-list">';
    if (sentences.length > 0) {
      for (const s of sentences) html += `<li>${TrialReport._formatLabeledBullet(s)}</li>`;
    } else {
      const groups = TrialReport._groupTraitsByPillar(items);
      for (const [pillar, traits] of Object.entries(groups)) {
        html += `<li><strong>${pillar}:</strong> ${traits.join(', ')}</li>`;
      }
    }
    html += '</ul></div></div>';
    return html;
  },

  // ── Coaching Staff Assessment (framed band) ───────────────

  _renderCoachAssessment(ev) {
    const text = ev.coachAssessment || ev.coachNotesRaw || '';
    if (!text) return '';

    return `
      <div class="rpt-coach-band">
        <div class="rpt-heading">Coaching Staff Assessment</div>
        <div class="rpt-coach-quote">
          <p class="rpt-coach-text">${TrialReport._esc(text)}</p>
        </div>
      </div>`;
  },

  // ── Claude API ────────────────────────────────────────────

  _getApiKey() {
    let key = localStorage.getItem('itp_claude_api_key');
    if (!key) {
      key = window.prompt('Enter your Claude API key.\n\nGet one at: console.anthropic.com/settings/keys\nIt will be saved locally in your browser.');
      if (key) localStorage.setItem('itp_claude_api_key', key.trim());
    }
    return key ? key.trim() : null;
  },

  async _generateTraitSentences() {
    const ev = TrialReport._evaluation;
    const player = TrialReport._player;
    const hasStrengths = ev.strengths.length > 0;
    const hasAreas = ev.areasOfOpportunity.length > 0;
    if (!hasStrengths && !hasAreas) return;

    const apiKey = TrialReport._getApiKey();
    if (!apiKey) return;

    const positions = (player.positions || []).map(p => typeof p === 'string' ? p : p.code).join(', ') || 'unknown';
    const strengthLabels = ev.strengths.map(k => TrialReport._traitLabel(k));
    const areaLabels = ev.areasOfOpportunity.map(k => TrialReport._traitLabel(k));

    try {
      const response = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-api-key': apiKey,
          'anthropic-version': '2023-06-01',
          'anthropic-dangerous-direct-browser-access': 'true'
        },
        body: JSON.stringify({
          model: 'claude-haiku-4-5-20251001',
          max_tokens: 512,
          system: `You are writing bullet points for a youth football (soccer) player evaluation report shared with the player and their parents.

Given a player's position, their strengths, and their areas of opportunity, write natural sentences that describe each group. Rules:
- Write exactly 3 items for strengths and exactly 3 for areas of opportunity
- Each item MUST start with a short label (1-3 words) followed by a colon, then the description. Example: "Game Understanding: Ian reads the game well and positions himself intelligently in midfield"
- The label should summarize the key trait in that bullet point
- Group related traits into one item naturally
- Be specific to the player's position. Reference training situations and practice scenarios only (NOT match/game situations, as we only see trial players in training sessions)
- Use simple language a teenager and parents can understand
- Do NOT use superlatives like "excellent", "exceptional", "outstanding". Use grounded words like "solid", "comfortable", "good", "showed"
- Do NOT use dashes as punctuation
- For areas of opportunity, frame positively. Focus on what the player can improve, not what they lack
- Use the player's first name instead of "he", "the player", or "you"

Also write a "decisionSummary": one short sentence (max 20 words) explaining the decision. Focus on the player's personality, character, attitude, and their potential to be developed. Do not focus on current skill level.

Return a JSON object: {"strengths": ["Label: description", ...], "areas": ["Label: description", ...], "decisionSummary": "sentence"}. No markdown.`,
          messages: [{
            role: 'user',
            content: `Player name: ${player.firstName}\nPosition: ${positions}\nStrengths: ${strengthLabels.join(', ') || 'none'}\nAreas of Opportunity: ${areaLabels.join(', ') || 'none'}\nDecision: ${ev.recommendation === 'accepted' ? 'Accepted' : ev.recommendation === 'not-accepted' ? 'Not Accepted' : 'pending'}\nCoach assessment: ${ev.coachAssessment || ev.coachNotesRaw || 'none'}`
          }]
        })
      });

      if (!response.ok) {
        if (response.status === 401) localStorage.removeItem('itp_claude_api_key');
        return;
      }

      const data = await response.json();
      let content = data.content?.[0]?.text || '{}';
      content = content.replace(/```json\s*/gi, '').replace(/```\s*/g, '').trim();
      const result = JSON.parse(content);

      if (result.strengths) ev.strengthsSentences = result.strengths;
      if (result.areas) ev.areasSentences = result.areas;
      if (result.decisionSummary) ev.decisionSummary = result.decisionSummary;
    } catch (err) {
      console.error('Trait sentence generation error:', err);
    }
  },

  async _polishAssessment(container) {
    const ev = TrialReport._evaluation;
    const player = TrialReport._player;
    const rawNotes = container.querySelector('#trl-coach-notes')?.value?.trim();

    if (!rawNotes) { App.toast('Write your impressions first'); return; }

    const apiKey = TrialReport._getApiKey();
    if (!apiKey) return;

    const btn = container.querySelector('#trl-btn-polish');
    const originalHTML = btn.innerHTML;
    btn.innerHTML = '<span class="ai-spinner"></span> Polishing...';
    btn.classList.add('loading');
    btn.disabled = true;

    const strengthLabels = ev.strengths.map(k => TrialReport._traitLabel(k));
    const areaLabels = ev.areasOfOpportunity.map(k => TrialReport._traitLabel(k));
    const positions = (player.positions || []).map(p => typeof p === 'string' ? p : p.code).join(', ') || 'unknown';

    try {
      const response = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-api-key': apiKey,
          'anthropic-version': '2023-06-01',
          'anthropic-dangerous-direct-browser-access': 'true'
        },
        body: JSON.stringify({
          model: 'claude-haiku-4-5-20251001',
          max_tokens: 512,
          system: `You are a football (soccer) youth development coach writing a "Coaching Staff Assessment" paragraph for a player evaluation report. This report is shared with the player and their parents.

Take the coach's rough notes and turn them into one short paragraph (2-3 sentences). Rules:
- Use the coach's own observations as the main content — don't invent things they didn't say
- Weave in the player's strengths and areas of opportunity naturally where they fit
- Use simple, clear language that a teenager and their parents can understand
- Be professional but friendly — like a coach speaking to a family
- Be honest and balanced — mention both positives and areas to grow
- Tailor to the player's position. Only reference training sessions and practice, NOT matches or games (we don't see trial players in matches)
- Do NOT overpromise or make guarantees
- Do NOT use superlatives or hype words like "excellent", "exceptional", "outstanding", "remarkable", "incredible", "phenomenal", "tremendous". Use grounded words like "solid", "good", "showed", "demonstrated", "comfortable", "capable"
- Sound like a real coaching staff, not a computer
- ALWAYS include a sentence about the player's character, attitude, or personality — how they are as a person, how they interact with teammates, their coachability, work ethic, or attitude. This is the most important thing we evaluate.
- NEVER use em dashes (—) or hyphens (-) as punctuation in the text. Use commas, periods, and simple sentence structures instead. Dashes make it look AI generated.

Return ONLY the paragraph as plain text. No quotes, no JSON, no markdown.`,
          messages: [{
            role: 'user',
            content: `Player: ${player.firstName} ${player.lastName}, Position: ${positions}
Strengths: ${strengthLabels.join(', ') || 'none selected'}
Areas of Opportunity: ${areaLabels.join(', ') || 'none selected'}
Coach's notes: ${rawNotes}`
          }]
        })
      });

      if (!response.ok) {
        if (response.status === 401) {
          localStorage.removeItem('itp_claude_api_key');
          throw new Error('Invalid API key. Please try again.');
        }
        const err = await response.json().catch(() => ({}));
        throw new Error(err.error?.message || `API error (${response.status})`);
      }

      const data = await response.json();
      const text = (data.content?.[0]?.text || '').trim();

      if (text) {
        ev.coachAssessment = text;
        ev.coachNotesRaw = rawNotes;
        const assessmentEl = container.querySelector('#trl-coach-assessment');
        assessmentEl.value = text;
        assessmentEl.style.display = '';
        App.toast('Assessment polished');
      }
    } catch (err) {
      console.error('Polish error:', err);
      App.toast(err.message || 'Polishing failed');
    } finally {
      btn.innerHTML = originalHTML;
      btn.classList.remove('loading');
      btn.disabled = false;
    }
  },

  // ── Recommendation Banner ──────────────────────────────────

  _renderRecommendation(ev) {
    if (!ev.recommendation && !ev.decisionSummary) return '';

    const labels = { accepted: 'ACCEPTED', 'not-accepted': 'NOT ACCEPTED' };
    const label = labels[ev.recommendation] || '';
    const bannerClass = ev.recommendation === 'accepted' ? 'trl-rec-banner-accepted' : ev.recommendation === 'not-accepted' ? 'trl-rec-banner-not-accepted' : '';

    const nextSteps = ev.recommendation === 'accepted'
      ? 'Our administration team will follow up with an official offer and enrollment details shortly.'
      : ev.recommendation === 'not-accepted'
      ? 'We appreciate the time and effort during the trial period. We encourage continued development and wish the best for the future.'
      : '';

    return `
      <div class="rpt-rec-section">
        <div class="rpt-section">
          <div class="rpt-heading">Decision</div>
          ${label ? `<div class="trl-rec-banner ${bannerClass}">${label}</div>` : ''}
          ${ev.decisionSummary ? `<p class="trl-rec-text">${TrialReport._esc(ev.decisionSummary)}</p>` : ''}
          ${nextSteps ? `<p class="trl-next-steps">${nextSteps}</p>` : ''}
        </div>
      </div>`;
  },

  // ── Footer ──────────────────────────────────────────────────

  _renderFooter(player) {
    return `
      <div class="rpt-footer">
        <img src="assets/logos/fc-fs-black.png" alt="" class="rpt-footer-logo">
        <span class="rpt-footer-text">ITP Trial Evaluation &mdash; ${player.firstName} ${player.lastName} &mdash; 1. FC K&ouml;ln International Talent Pathway</span>
      </div>
      <div class="rpt-page-accent"></div>`;
  },

  // ── PDF Export ──────────────────────────────────────────────

  _exportPDF() {
    const scripts = [
      { global: 'html2canvas', src: 'https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js' },
      { global: 'jspdf', src: 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js' }
    ];
    const toLoad = scripts.filter(s => typeof window[s.global] === 'undefined');

    if (toLoad.length === 0) {
      TrialReport._doPDFExport();
      return;
    }

    let loaded = 0;
    toLoad.forEach(s => {
      const script = document.createElement('script');
      script.src = s.src;
      script.onload = () => { loaded++; if (loaded === toLoad.length) TrialReport._doPDFExport(); };
      document.head.appendChild(script);
    });
  },

  async _doPDFExport() {
    const player = TrialReport._player;
    const filename = `ITP_Trial_Report_${player.firstName}_${player.lastName}.pdf`;

    const pages = document.querySelectorAll('#trl-report-pages .rpt-page');
    if (!pages.length) return;

    const btn = document.getElementById('trl-btn-export-pdf');
    if (btn) { btn.disabled = true; btn.textContent = 'Exporting...'; }

    try {
      const PDF = new jspdf.jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });
      const pageWidth = 210;
      const pageHeight = 297;
      let firstPage = true;

      for (let i = 0; i < pages.length; i++) {
        const source = pages[i];
        source.scrollIntoView({ block: 'start' });
        await new Promise(r => setTimeout(r, 150));

        const canvas = await html2canvas(source, {
          scale: 2,
          useCORS: true,
          allowTaint: true,
          logging: false,
          backgroundColor: '#ffffff'
        });

        const imgData = canvas.toDataURL('image/jpeg', 0.95);
        const imgHeightMm = (canvas.height * pageWidth) / canvas.width;

        // Slice tall content across multiple A4 pages using negative Y offsets;
        // each PDF page crops at its bounds, so the image effectively scrolls.
        let consumed = 0;
        while (consumed < imgHeightMm) {
          if (!firstPage) PDF.addPage();
          firstPage = false;
          PDF.addImage(imgData, 'JPEG', 0, -consumed, pageWidth, imgHeightMm);
          consumed += pageHeight;
        }
      }

      PDF.save(filename);
      App.toast('PDF exported');
    } catch (err) {
      console.error('PDF export error:', err);
      alert('PDF export failed: ' + err.message);
    } finally {
      if (btn) { btn.disabled = false; btn.textContent = 'Export PDF'; }
    }
  },

  // ── Helpers ─────────────────────────────────────────────────

  _formatLabeledBullet(str) {
    const colonIdx = str.indexOf(':');
    if (colonIdx > 0 && colonIdx < 40) {
      const label = str.slice(0, colonIdx);
      const desc = str.slice(colonIdx + 1).trim();
      return `<strong>${TrialReport._esc(label)}:</strong> ${TrialReport._esc(desc)}`;
    }
    return TrialReport._esc(str);
  },

  _esc(str) {
    if (!str) return '';
    const div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
  }
};
