'use strict';

/* ═══════════════════════════════════════════════════════════════
   trial-report.js — Trial Evaluation Report: builder, preview, PDF
   - Strengths & Areas of Opportunity via trait chip selection
   - Development Plan auto-generated by Claude API from traits
═══════════════════════════════════════════════════════════════ */

const TrialReport = {

  _player: null,
  _evaluation: null,

  init() {},

  // ── Entry Point ─────────────────────────────────────────────

  show(playerId) {
    const player = DB.get(playerId);
    if (!player) { location.hash = '#roster'; return; }

    TrialReport._player = player;
    TrialReport._evaluation = player.trialEvaluation
      ? JSON.parse(JSON.stringify(player.trialEvaluation))
      : TrialReport._emptyEvaluation();

    // Migrate old format
    if (TrialReport._evaluation.traits && !TrialReport._evaluation.strengths) {
      const old = TrialReport._evaluation;
      const ev = TrialReport._emptyEvaluation();
      // Pull strengths/weaknesses from old traits format
      if (old.traits) {
        for (const pillar of Object.values(old.traits)) {
          if (pillar.strengths) ev.strengths.push(...pillar.strengths);
          if (pillar.weaknesses) ev.areasOfOpportunity.push(...pillar.weaknesses);
        }
      }
      ev.generalNotes = old.generalNotes || '';
      ev.recommendation = old.recommendation || '';
      ev.recommendationSummary = old.recommendationSummary || '';
      TrialReport._evaluation = ev;
    }

    const container = document.getElementById('trial-report-content');
    container.innerHTML = TrialReport._renderBuilder(player);
    TrialReport._bindEvents(container);
  },

  _emptyEvaluation() {
    return {
      strengths: [],
      strengthsSentences: [],
      areasOfOpportunity: [],
      areasSentences: [],
      coachNotesRaw: '',
      coachAssessment: '',
      recommendation: '',
      recommendationSummary: ''
    };
  },

  // ══════════════════════════════════════════════════════════════
  //  BUILDER FORM
  // ══════════════════════════════════════════════════════════════

  _renderBuilder(player) {
    const name = `${player.firstName} ${player.lastName}`;
    const ev = TrialReport._evaluation;

    return `
      <div class="report-builder">
        <div class="back-row">
          <button class="btn-back" onclick="location.hash='#profile/${player.id}'">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"><polyline points="15 18 9 12 15 6"/></svg>
            Back to Profile
          </button>
        </div>

        <div class="report-builder-header">
          <h2>Trial Evaluation Report</h2>
          <p class="report-builder-sub">${name} &middot; ${player.ageGroup || '—'}</p>
        </div>

        <!-- ── Trait Selection ──────────────────────────────── -->
        <div class="report-section">
          <div class="report-section-title">Player Evaluation</div>
          <p class="report-section-desc">Click to cycle: <span class="trl-legend-s">Strength</span> <span class="trl-legend-a">Area of Opportunity</span></p>
          ${TrialReport._renderTraitSelectors()}
        </div>

        <!-- ── Coaching Staff Assessment ──────────────────────────── -->
        <div class="report-section">
          <div class="report-section-title">Coaching Staff Assessment</div>
          <p class="report-section-desc">Write your impressions of the player, then polish with AI</p>
          <textarea class="report-textarea" id="trl-coach-notes" rows="4" placeholder="Type your rough impressions of the player...">${TrialReport._esc(ev.coachNotesRaw)}</textarea>
          <div class="trl-ai-row">
            <button class="btn btn-ai-generate" id="trl-btn-polish">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/></svg>
              Polish with AI
            </button>
            <button class="btn-reset-key" id="trl-btn-reset-key">Reset API Key</button>
          </div>
          <textarea class="report-textarea trl-assessment-result" id="trl-coach-assessment" rows="6" placeholder="Polished assessment will appear here. You can edit it before exporting." ${ev.coachAssessment ? '' : 'style="display:none"'}>${TrialReport._esc(ev.coachAssessment)}</textarea>
        </div>

        <!-- ── Recommendation ─────────────────────────────── -->
        <div class="report-section">
          <div class="report-section-title">Recommendation</div>
          <div class="trl-rec-toggle" id="trl-rec-toggle">
            <button type="button" class="trl-rec-btn trl-rec-offer ${ev.recommendation === 'offer' ? 'active' : ''}" data-rec="offer">Offer</button>
            <button type="button" class="trl-rec-btn trl-rec-revisit ${ev.recommendation === 'revisit' ? 'active' : ''}" data-rec="revisit">Revisit</button>
            <button type="button" class="trl-rec-btn trl-rec-pass ${ev.recommendation === 'pass' ? 'active' : ''}" data-rec="pass">Pass</button>
          </div>
          <textarea class="report-textarea" id="trl-rec-summary" rows="3" placeholder="Summary / reasoning..." style="margin-top:10px">${TrialReport._esc(ev.recommendationSummary)}</textarea>
        </div>

        <!-- ── Actions ────────────────────────────────────── -->
        <div class="report-actions">
          <button class="btn btn-outline" id="trl-btn-save">Save Draft</button>
          <button class="btn btn-primary" id="trl-btn-preview">Preview Report</button>
        </div>

        <div id="trial-report-preview-area"></div>
      </div>`;
  },

  _renderTraitSelectors() {
    const ev = TrialReport._evaluation;
    let html = '';

    for (const [pillarKey, pillar] of Object.entries(REPORT_TRAITS)) {
      html += `<div class="trait-pillar">
        <div class="trait-pillar-label">${pillar.label}</div>
        <div class="trait-grid">`;

      for (const [traitKey, traitLabel] of Object.entries(pillar.traits)) {
        let mode = '';
        if (ev.strengths.includes(traitKey)) mode = 'strength';
        else if (ev.areasOfOpportunity.includes(traitKey)) mode = 'area';

        html += `<span class="trait-chip" data-pillar="${pillarKey}" data-trait="${traitKey}" ${mode ? `data-mode="${mode}"` : ''}>${traitLabel}</span>`;
      }

      html += '</div></div>';
    }

    return html;
  },

  // ── Events ──────────────────────────────────────────────────

  _bindEvents(container) {
    // Trait chip click — cycle: none → strength → area → none
    container.querySelectorAll('.trait-chip').forEach(chip => {
      chip.addEventListener('click', () => {
        const trait = chip.dataset.trait;
        const current = chip.dataset.mode || '';
        const ev = TrialReport._evaluation;

        // Remove from both arrays
        ev.strengths = ev.strengths.filter(t => t !== trait);
        ev.areasOfOpportunity = ev.areasOfOpportunity.filter(t => t !== trait);

        if (current === '') {
          ev.strengths.push(trait);
          chip.dataset.mode = 'strength';
        } else if (current === 'strength') {
          ev.areasOfOpportunity.push(trait);
          chip.dataset.mode = 'area';
        } else {
          delete chip.dataset.mode;
        }
      });
    });

    // Polish with AI
    container.querySelector('#trl-btn-polish').addEventListener('click', () => {
      TrialReport._polishAssessment(container);
    });

    // Reset API key
    container.querySelector('#trl-btn-reset-key').addEventListener('click', () => {
      localStorage.removeItem('itp_claude_api_key');
      App.toast('API key cleared');
    });

    // Recommendation toggle
    container.querySelector('#trl-rec-toggle').addEventListener('click', e => {
      const btn = e.target.closest('.trl-rec-btn');
      if (!btn) return;
      const isActive = btn.classList.contains('active');
      container.querySelectorAll('.trl-rec-btn').forEach(b => b.classList.remove('active'));
      if (!isActive) {
        btn.classList.add('active');
        TrialReport._evaluation.recommendation = btn.dataset.rec;
      } else {
        TrialReport._evaluation.recommendation = '';
      }
    });

    // Save draft
    container.querySelector('#trl-btn-save').addEventListener('click', () => {
      TrialReport._syncFormData(container);
      TrialReport._saveDraft();
      App.toast('Draft saved');
    });

    // Preview
    container.querySelector('#trl-btn-preview').addEventListener('click', async () => {
      TrialReport._syncFormData(container);
      TrialReport._saveDraft();
      const btn = container.querySelector('#trl-btn-preview');
      btn.textContent = 'Generating...';
      btn.disabled = true;
      await TrialReport._generateTraitSentences();
      TrialReport._saveDraft();
      btn.textContent = 'Preview Report';
      btn.disabled = false;
      TrialReport._showPreview(container);
    });
  },

  _syncFormData(container) {
    const ev = TrialReport._evaluation;
    ev.coachNotesRaw = container.querySelector('#trl-coach-notes')?.value || '';
    ev.coachAssessment = container.querySelector('#trl-coach-assessment')?.value || '';
    ev.recommendationSummary = container.querySelector('#trl-rec-summary')?.value || '';
  },

  _saveDraft() {
    const player = TrialReport._player;
    player.trialEvaluation = TrialReport._evaluation;
    DB.save(player);
  },

  // ══════════════════════════════════════════════════════════════
  //  TRAIT → BULLET POINT FORMATTING
  // ══════════════════════════════════════════════════════════════

  _traitLabel(traitKey) {
    for (const pillar of Object.values(REPORT_TRAITS)) {
      if (pillar.traits[traitKey]) return pillar.traits[traitKey];
    }
    return traitKey;
  },

  _traitPillar(traitKey) {
    for (const [pk, pillar] of Object.entries(REPORT_TRAITS)) {
      if (pillar.traits[traitKey]) return pillar.label;
    }
    return '';
  },

  _groupTraitsByPillar(traitKeys) {
    const groups = {};
    for (const key of traitKeys) {
      const pillar = TrialReport._traitPillar(key);
      if (!groups[pillar]) groups[pillar] = [];
      groups[pillar].push(TrialReport._traitLabel(key));
    }
    return groups;
  },

  // ══════════════════════════════════════════════════════════════
  //  A4 PREVIEW
  // ══════════════════════════════════════════════════════════════

  _showPreview(container) {
    const player = TrialReport._player;
    const ev = TrialReport._evaluation;
    const meta = DB.getMeta();
    const seasonLabel = `20${meta.activeSeason}`;

    const previewArea = container.querySelector('#trial-report-preview-area');

    previewArea.innerHTML = `
      <div class="report-preview-toolbar">
        <button class="btn btn-primary" id="trl-btn-export-pdf">Export PDF</button>
        <button class="btn btn-outline" id="trl-btn-close-preview">Close Preview</button>
      </div>
      <div class="report-preview-scroll">
        <div class="report-pages" id="trl-report-pages">
          <div class="rpt-page">
            ${TrialReport._renderHeader(seasonLabel)}
            ${TrialReport._renderPlayerHero(player)}
            <hr class="rpt-divider">
            ${TrialReport._renderStrengths(ev)}
            ${TrialReport._renderAreas(ev)}
            ${TrialReport._renderCoachAssessment(ev)}
            ${TrialReport._renderRecommendation(ev)}
            ${TrialReport._renderFooter(player)}
          </div>
        </div>
      </div>`;

    previewArea.scrollIntoView({ behavior: 'smooth' });

    previewArea.querySelector('#trl-btn-export-pdf').addEventListener('click', () => {
      TrialReport._exportPDF();
    });

    previewArea.querySelector('#trl-btn-close-preview').addEventListener('click', () => {
      previewArea.innerHTML = '';
    });
  },

  // ── Header Banner ───────────────────────────────────────────

  _renderHeader(seasonLabel) {
    return `
      <div class="rpt-header-banner">
        <img src="assets/logos/koln-fs.webp" alt="" class="rpt-logo">
        <div class="rpt-header-banner-text">
          <div class="rpt-title">Trial Evaluation</div>
          <div class="rpt-subtitle">International Talent Program</div>
        </div>
        <div class="rpt-header-right">
          <div class="rpt-season">${seasonLabel}</div>
          <div class="rpt-date">${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</div>
        </div>
      </div>`;
  },

  // ── Player Hero ─────────────────────────────────────────────

  _renderPlayerHero(player) {
    const age = App.computeAge(player.dateOfBirth);
    const dob = player.dateOfBirth ? new Date(player.dateOfBirth + 'T12:00:00').toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }) : '—';
    const positions = (player.positions || []).map(p => typeof p === 'string' ? p : p.code).join(' / ') || '—';
    const initials = (player.firstName?.[0] || '') + (player.lastName?.[0] || '');

    const posY = player.photoPositionY ?? 25;
    const photoHTML = player.photoBase64
      ? `<img src="${player.photoBase64}" alt="" class="rpt-player-photo" style="object-position: center ${posY}%">`
      : `<div class="rpt-player-initials">${initials}</div>`;

    let trialPeriod = '—';
    if (player.trialDates?.start && player.trialDates?.end) {
      const fmtDate = (iso) => new Date(iso + 'T12:00:00').toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
      trialPeriod = `${fmtDate(player.trialDates.start)} – ${fmtDate(player.trialDates.end)}, ${new Date(player.trialDates.end + 'T12:00:00').getFullYear()}`;
    } else if (player.trialDates?.start) {
      trialPeriod = new Date(player.trialDates.start + 'T12:00:00').toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
    }

    return `
      <div class="rpt-player-hero">
        <div class="rpt-player-hero-inner">
          ${photoHTML}
          <div class="rpt-player-details">
            <div class="rpt-player-name">${player.firstName} <span class="rpt-player-surname">${player.lastName}</span></div>
            <div class="rpt-player-meta">${player.ageGroup || '—'} &middot; ${positions} &middot; ${player.nationality || '—'}</div>
            <div class="rpt-info-grid">
              <div class="rpt-info-row"><span class="rpt-info-label">Date of Birth</span><span class="rpt-info-value">${dob}</span></div>
              <div class="rpt-info-row"><span class="rpt-info-label">Age</span><span class="rpt-info-value">${age || '—'}</span></div>
              <div class="rpt-info-row"><span class="rpt-info-label">Foot</span><span class="rpt-info-value">${player.foot || '—'}</span></div>
              <div class="rpt-info-row"><span class="rpt-info-label">Trial Period</span><span class="rpt-info-value">${trialPeriod}</span></div>
            </div>
          </div>
        </div>
      </div>`;
  },

  // ── Strengths ─────────────────────────────────────────────

  _renderStrengths(ev) {
    if (!ev.strengths || ev.strengths.length === 0) return '';

    const sentences = ev.strengthsSentences || [];
    let html = '<div class="rpt-section"><div class="rpt-heading">Strengths</div><ul class="rpt-bullet-list">';

    if (sentences.length > 0) {
      for (const s of sentences) html += `<li>${TrialReport._esc(s)}</li>`;
    } else {
      const groups = TrialReport._groupTraitsByPillar(ev.strengths);
      for (const [pillar, traits] of Object.entries(groups)) {
        html += `<li><strong>${pillar}:</strong> ${traits.join(', ')}</li>`;
      }
    }

    html += '</ul></div>';
    return html;
  },

  // ── Areas of Opportunity ──────────────────────────────────

  _renderAreas(ev) {
    if (!ev.areasOfOpportunity || ev.areasOfOpportunity.length === 0) return '';

    const sentences = ev.areasSentences || [];
    let html = '<div class="rpt-section"><div class="rpt-heading">Areas of Opportunity</div><ul class="rpt-bullet-list">';

    if (sentences.length > 0) {
      for (const s of sentences) html += `<li>${TrialReport._esc(s)}</li>`;
    } else {
      const groups = TrialReport._groupTraitsByPillar(ev.areasOfOpportunity);
      for (const [pillar, traits] of Object.entries(groups)) {
        html += `<li><strong>${pillar}:</strong> ${traits.join(', ')}</li>`;
      }
    }

    html += '</ul></div>';
    return html;
  },

  // ── Coaching Staff Assessment ─────────────────────────────────────

  _renderCoachAssessment(ev) {
    const text = ev.coachAssessment || ev.coachNotesRaw || '';
    if (!text) return '';

    return `
      <div class="rpt-section">
        <div class="rpt-heading">Coaching Staff Assessment</div>
        <p class="rpt-text-fallback">${TrialReport._esc(text)}</p>
      </div>`;
  },

  // ── Claude API ────────────────────────────────────────────

  _getApiKey() {
    let key = localStorage.getItem('itp_claude_api_key');
    if (!key) {
      key = window.prompt('Enter your Claude API key.\n\nGet one at: console.anthropic.com/settings/keys\nIt will be saved locally in your browser.');
      if (key) localStorage.setItem('itp_claude_api_key', key.trim());
    }
    return key ? key.trim() : null;
  },

  async _generateTraitSentences() {
    const ev = TrialReport._evaluation;
    const player = TrialReport._player;
    const hasStrengths = ev.strengths.length > 0;
    const hasAreas = ev.areasOfOpportunity.length > 0;
    if (!hasStrengths && !hasAreas) return;

    const apiKey = TrialReport._getApiKey();
    if (!apiKey) return;

    const positions = (player.positions || []).map(p => typeof p === 'string' ? p : p.code).join(', ') || 'unknown';
    const strengthLabels = ev.strengths.map(k => TrialReport._traitLabel(k));
    const areaLabels = ev.areasOfOpportunity.map(k => TrialReport._traitLabel(k));

    try {
      const response = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-api-key': apiKey,
          'anthropic-version': '2023-06-01',
          'anthropic-dangerous-direct-browser-access': 'true'
        },
        body: JSON.stringify({
          model: 'claude-haiku-4-5-20251001',
          max_tokens: 512,
          system: `You are writing bullet points for a youth football (soccer) player evaluation report shared with the player and their parents.

Given a player's position, their strengths, and their areas of opportunity, write natural sentences that describe each group. Rules:
- Write exactly 3 sentences for strengths and exactly 3 for areas of opportunity
- Group related traits into one sentence naturally
- Be specific to the player's position. Mention real game situations (e.g., "when receiving the ball in midfield", "during 1v1 defending on the wing")
- Use simple language a teenager and parents can understand
- Do NOT use superlatives like "excellent", "exceptional", "outstanding". Use grounded words like "solid", "comfortable", "good", "showed"
- Do NOT use dashes as punctuation
- For areas of opportunity, frame positively. Focus on what the player can improve, not what they lack
- Use the player's first name instead of "he", "the player", or "you"

Return a JSON object with two arrays: {"strengths": ["sentence1", ...], "areas": ["sentence1", ...]}. No markdown.`,
          messages: [{
            role: 'user',
            content: `Player name: ${player.firstName}\nPosition: ${positions}\nStrengths: ${strengthLabels.join(', ') || 'none'}\nAreas of Opportunity: ${areaLabels.join(', ') || 'none'}`
          }]
        })
      });

      if (!response.ok) {
        if (response.status === 401) localStorage.removeItem('itp_claude_api_key');
        return;
      }

      const data = await response.json();
      let content = data.content?.[0]?.text || '{}';
      content = content.replace(/```json\s*/gi, '').replace(/```\s*/g, '').trim();
      const result = JSON.parse(content);

      if (result.strengths) ev.strengthsSentences = result.strengths;
      if (result.areas) ev.areasSentences = result.areas;
    } catch (err) {
      console.error('Trait sentence generation error:', err);
    }
  },

  async _polishAssessment(container) {
    const ev = TrialReport._evaluation;
    const player = TrialReport._player;
    const rawNotes = container.querySelector('#trl-coach-notes')?.value?.trim();

    if (!rawNotes) { App.toast('Write your impressions first'); return; }

    const apiKey = TrialReport._getApiKey();
    if (!apiKey) return;

    const btn = container.querySelector('#trl-btn-polish');
    const originalHTML = btn.innerHTML;
    btn.innerHTML = '<span class="ai-spinner"></span> Polishing...';
    btn.classList.add('loading');
    btn.disabled = true;

    const strengthLabels = ev.strengths.map(k => TrialReport._traitLabel(k));
    const areaLabels = ev.areasOfOpportunity.map(k => TrialReport._traitLabel(k));
    const positions = (player.positions || []).map(p => typeof p === 'string' ? p : p.code).join(', ') || 'unknown';

    try {
      const response = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-api-key': apiKey,
          'anthropic-version': '2023-06-01',
          'anthropic-dangerous-direct-browser-access': 'true'
        },
        body: JSON.stringify({
          model: 'claude-haiku-4-5-20251001',
          max_tokens: 512,
          system: `You are a football (soccer) youth development coach writing a "Coaching Staff Assessment" paragraph for a player evaluation report. This report is shared with the player and their parents.

Take the coach's rough notes and turn them into one concise paragraph (3-4 sentences). Rules:
- Use the coach's own observations as the main content — don't invent things they didn't say
- Weave in the player's strengths and areas of opportunity naturally where they fit
- Use simple, clear language that a teenager and their parents can understand
- Be professional but friendly — like a coach speaking to a family
- Be honest and balanced — mention both positives and areas to grow
- Tailor to the player's position on the pitch
- Do NOT overpromise or make guarantees
- Do NOT use superlatives or hype words like "excellent", "exceptional", "outstanding", "remarkable", "incredible", "phenomenal", "tremendous". Use grounded words like "solid", "good", "showed", "demonstrated", "comfortable", "capable"
- Sound like a real coaching staff, not a computer
- ALWAYS include a sentence about the player's character, attitude, or personality — how they are as a person, how they interact with teammates, their coachability, work ethic, or attitude. This is the most important thing we evaluate.
- NEVER use em dashes (—) or hyphens (-) as punctuation in the text. Use commas, periods, and simple sentence structures instead. Dashes make it look AI generated.

Return ONLY the paragraph as plain text. No quotes, no JSON, no markdown.`,
          messages: [{
            role: 'user',
            content: `Player: ${player.firstName} ${player.lastName}, Position: ${positions}
Strengths: ${strengthLabels.join(', ') || 'none selected'}
Areas of Opportunity: ${areaLabels.join(', ') || 'none selected'}
Coach's notes: ${rawNotes}`
          }]
        })
      });

      if (!response.ok) {
        if (response.status === 401) {
          localStorage.removeItem('itp_claude_api_key');
          throw new Error('Invalid API key. Please try again.');
        }
        const err = await response.json().catch(() => ({}));
        throw new Error(err.error?.message || `API error (${response.status})`);
      }

      const data = await response.json();
      const text = (data.content?.[0]?.text || '').trim();

      if (text) {
        ev.coachAssessment = text;
        ev.coachNotesRaw = rawNotes;
        const assessmentEl = container.querySelector('#trl-coach-assessment');
        assessmentEl.value = text;
        assessmentEl.style.display = '';
        App.toast('Assessment polished');
      }
    } catch (err) {
      console.error('Polish error:', err);
      App.toast(err.message || 'Polishing failed');
    } finally {
      btn.innerHTML = originalHTML;
      btn.classList.remove('loading');
      btn.disabled = false;
    }
  },

  // ── Recommendation Banner ──────────────────────────────────

  _renderRecommendation(ev) {
    if (!ev.recommendation && !ev.recommendationSummary) return '';

    const labels = { offer: 'OFFER', revisit: 'REVISIT', pass: 'PASS' };
    const label = labels[ev.recommendation] || '';

    return `
      <div class="rpt-section">
        <div class="rpt-heading">Recommendation</div>
        ${label ? `<div class="trl-rec-banner trl-rec-banner-${ev.recommendation}">${label}</div>` : ''}
        ${ev.recommendationSummary ? `<p class="trl-rec-text">${TrialReport._esc(ev.recommendationSummary)}</p>` : ''}
      </div>`;
  },

  // ── Footer ──────────────────────────────────────────────────

  _renderFooter(player) {
    return `
      <div class="rpt-footer">
        <img src="assets/logos/koln-fs.webp" alt="" class="rpt-footer-logo">
        <span class="rpt-footer-text">ITP Trial Evaluation &mdash; ${player.firstName} ${player.lastName} &mdash; 1. FC K&ouml;ln Football School</span>
      </div>
      <div class="rpt-page-accent"></div>`;
  },

  // ── PDF Export ──────────────────────────────────────────────

  _exportPDF() {
    const pages = document.getElementById('trl-report-pages');
    if (!pages) return;

    if (typeof html2pdf === 'undefined') {
      const script = document.createElement('script');
      script.src = 'https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js';
      script.onload = () => TrialReport._doPDFExport(pages);
      document.head.appendChild(script);
    } else {
      TrialReport._doPDFExport(pages);
    }
  },

  _doPDFExport(element) {
    const player = TrialReport._player;
    const filename = `ITP_Trial_Report_${player.firstName}_${player.lastName}.pdf`;

    html2pdf()
      .set({
        margin: 0,
        filename,
        image: { type: 'jpeg', quality: 0.95 },
        html2canvas: { scale: 2, useCORS: true, logging: false },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        pagebreak: { mode: ['css', 'legacy'], avoid: '.rpt-section' }
      })
      .from(element)
      .save()
      .then(() => App.toast('PDF exported'))
      .catch(err => {
        console.error('PDF export error:', err);
        alert('PDF export failed. Check console for details.');
      });
  },

  // ── Helpers ─────────────────────────────────────────────────

  _esc(str) {
    if (!str) return '';
    const div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
  }
};
